In [1]:
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.preprocessing import scale
from scipy.cluster import hierarchy
from scipy.cluster.hierarchy import fcluster

In [2]:
# Update the path for importing the data
df = pd.read_csv("C:\\Users\\MOUMITA\\Desktop\\Book2.csv")
df.head()

          Company Name  Avg_Rate_of_return  Risk (Standard dev.)
0  Adani Ports Sez Ltd            0.000633              0.026180
1      Apollo Hospital            0.001305              0.023315
2     Asian Paints Ltd            0.000677              0.017798
3            Axis Bank            0.000199              0.025445
4       Bajaj Auto Ltd            0.000302              0.017503

In [3]:
# Select three variables for clustering purpose
df1 = df.iloc[:, 1:3]
df1.head()

   Avg_Rate_of_return  Risk (Standard dev.)
0            0.000633              0.026180
1            0.001305              0.023315
2            0.000677              0.017798
3            0.000199              0.025445
4            0.000302              0.017503

In [4]:
# Standardization of features (Feature scaling)
scaler = StandardScaler()
X = scaler.fit_transform(df1)
X

array([[ 0.23711211,  1.47858042],
       [ 2.7600474 ,  0.68773996],
       [ 0.40355478, -0.83484997],
       [-1.39330114,  1.27579547],
       [-1.00609558, -0.91645745],
       [ 0.63480875,  1.63443101],
       [ 0.37158251,  1.20268315],
       [ 1.55003519, -0.05780037],
       [-0.876064  , -1.17045732],
       [-0.31873865, -0.87277139],
       [-0.18883089, -0.434671  ],
       [-0.06739554, -1.1371841 ],
       [-0.68757731,  0.26270647],
       [ 0.54796093,  0.25263422],
       [ 0.54777333, -0.72405774],
       [-0.5232246 , -0.74390773],
       [-0.95514482, -0.03309821],
       [ 0.68147078,  1.8853904 ],
       [-0.69313804, -1.41872622],
       [ 1.22730323,  0.46351826],
       [ 0.29201016, -0.54442988],
       [-0.94676621, -0.91266459],
       [ 1.17120073,  1.23902333],
       [-0.8537911 , -0.31920518],
       [-0.27081213, -0.55485458],
       [ 0.00907   ,  0.41017755],
       [-1.47486589,  0.08915596],
       [ 0.21515814, -1.62297951],
       [-0.70995903, -0.65602832],
       [-2.08970457,  1.3399633 ],
       [-0.29601548, -0.84048737],
       [ 0.28151908, -0.11037517],
       [ 0.06663585, -0.42014514],
       [ 0.28067485,  0.60301086],
       [-0.46573755, -0.36656541],
       [ 0.78409648, -0.67522446],
       [ 2.62253023, -0.23785218],
       [ 1.00739208,  2.9905229 ],
       [ 0.54443014,  1.55791472],
       [-0.37837945, -1.21923511],
       [-1.09464688, -0.15876324],
       [ 1.20621601, -0.15807572],
       [ 0.36945878, -0.48749503],
       [-1.34667288,  0.91942151],
       [-1.17517978, -0.66430709]])

In [5]:
# Fitting two clusters
kmeans = KMeans(n_clusters=4, n_init=10, random_state=0)  # create a k-means object
kmeans.fit(X)

C:\Users\MOUMITA\AppData\Roaming\Python\Python310\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

KMeans(n_clusters=4, n_init=10, random_state=0)

In [6]:
# Cluster membership
labels = kmeans.predict(X)
labels

array([3, 0, 2, 1, 2, 3, 3, 0, 2, 2, 2, 2, 1, 0, 2, 2, 1, 3, 2, 0, 2, 2,
       3, 2, 2, 1, 1, 2, 2, 1, 2, 2, 2, 3, 2, 0, 0, 3, 3, 2, 1, 0, 2, 1,
       2])

In [7]:
# Cluster description
df1['cluster'] = labels  # add cluster membership number as new column
df1['company'] = df['Company Name']
df1

    Avg_Rate_of_return  Risk (Standard dev.)  cluster              company
0             0.000633              0.026180        3  Adani Ports Sez Ltd
1             0.001305              0.023315        0      Apollo Hospital
2             0.000677              0.017798        2     Asian Paints Ltd
3             0.000199              0.025445        1            Axis Bank
4             0.000302              0.017503        2       Bajaj Auto Ltd
5             0.000739              0.026745        3        Bajaj Finance
6             0.000669              0.025181        3        Bajaj Finserv
7             0.000983              0.020614        0        Bharti Airtel
8             0.000336              0.016582        2            Britannia
9             0.000485              0.017661        2                Cipla
10            0.000520              0.019248        2           Divis Labs
11            0.000552              0.016703        2       Dr Reddys Labs
12            0.000387              0.021775        1        Eicher Motors
13            0.000716              0.021738        0               Grasim
14            0.000716              0.018200        2             HCL Tech
15            0.000430              0.018128        2            HDFC Bank
16            0.000315              0.020703        1            HDFC Life
17            0.000751              0.027654        3  Hindalco Industries
18            0.000385              0.015683        2                  HUL
19            0.000897              0.022502        0           ICICI Bank
20            0.000648              0.018851        2              Infosys
21            0.000318              0.017516        2                  ITC
22            0.000882              0.025312        3            JSW Steel
23            0.000342              0.019667        2       Kotak Mahindra
24            0.000498              0.018813        2               Larsen
25            0.000572              0.022309        1                  M&M
26            0.000177              0.021146        1        Maruti Suzuki
27            0.000627              0.014943        2               Nestle
28            0.000381              0.018446        2                 NTPC
29            0.000013              0.025678        1                 ONGC
30            0.000491              0.017778        2      Power Grid Corp
31            0.000645              0.020423        2             Reliance
32            0.000588              0.019301        2      SBI Life Insura
33            0.000645              0.023008        3                  SBI
34            0.000446              0.019495        2        Shree Cements
35            0.000779              0.018377        0           Sun Pharma
36            0.001269              0.019961        0      TATA Cons. Prod
37            0.000838              0.031658        3          Tata Motors
38            0.000715              0.026468        3           Tata Steel
39            0.000469              0.016406        2                  TCS
40            0.000278              0.020248        1        Tech Mahindra
41            0.000891              0.020250        0        Titan Company
42            0.000668              0.019057        2     UltraTech Cement
43            0.000211              0.024154        1                  UPL
44            0.000257              0.018416        2                Wipro

In [8]:
# Clusters
for i in range(4):
    print(f"Cluster {i}:")
    print(df1[df1['cluster'] == i])

df = df1[df1['cluster'] == 1]
df.drop('cluster', axis=1, inplace=True)

import random
from deap import base, creator, tools, algorithms

companies = {
    'Axis Bank': (0.000199, 0.025445),
    'Eicher Motors': (0.000387, 0.021775),
    'HDFC Life': (0.000315, 0.020703),
    'M&M': (0.000572, 0.022309),
    'Maruti Suzuki': (0.000177, 0.021146),
    'ONGC': (0.000013, 0.025678),
    'Tech Mahindra': (0.000278, 0.020248),
    'UPL': (0.000211, 0.024154)
}

POPULATION_SIZE = 50
NUM_GENERATIONS = 100
CXPB = 0.5
MUTPB = 0.2

def evaluate_portfolio(individual):
    total_return = sum(companies[company][0] for company, included in zip(companies.keys(), individual) if included)
    total_risk = sum(companies[company][1] for company, included in zip(companies.keys(), individual) if included)
    return total_return, total_risk

creator.create("FitnessMax", base.Fitness, weights=(1.0, -1.0))
creator.create("Individual", list, fitness=creator.FitnessMax)

toolbox = base.Toolbox()
toolbox.register("attr_bool", random.randint, 0, 1)
toolbox.register("individual", tools.initRepeat, creator.Individual, toolbox.attr_bool, len(companies))
toolbox.register("population", tools.initRepeat, list, toolbox.individual)

toolbox.register("evaluate", evaluate_portfolio)
toolbox.register("mate", tools.cxTwoPoint)
toolbox.register("mutate", tools.mutFlipBit, indpb=0.05)
toolbox.register("select", tools.selNSGA2)

population = toolbox.population(n=POPULATION_SIZE)

for gen in range(NUM_GENERATIONS):
    offspring = algorithms.varAnd(population, toolbox, cxpb=CXPB, mutpb=MUTPB)
    fits = toolbox.map(toolbox.evaluate, offspring)
    for fit, ind in zip(fits, offspring):
        ind.fitness.values = fit

    population = toolbox.select(offspring, k=len(population))

best_portfolio = tools.selBest(population, k=1)[0]

best_portfolio_companies = [company for company, included in zip(companies.keys(), best_portfolio) if included]
best_portfolio_return, best_portfolio_risk = evaluate_portfolio(best_portfolio)

print("Best Portfolio:", best_portfolio_companies)
print("Average Rate of Return:", best_portfolio_return)
print("Risk (Standard dev.):", best_portfolio_risk)

Cluster 0:
    Avg_Rate_of_return  Risk (Standard dev.)  cluster          company
1             0.001305              0.023315        0  Apollo Hospital
7             0.000983              0.020614        0    Bharti Airtel
13            0.000716              0.021738        0           Grasim
19            0.000897              0.022502        0       ICICI Bank
35            0.000779              0.018377        0       Sun Pharma
36            0.001269              0.019961        0  TATA Cons. Prod
41            0.000891              0.020250        0    Titan Company
Cluster 1:
    Avg_Rate_of_return  Risk (Standard dev.)  cluster        company
3             0.000199              0.025445        1      Axis Bank
12            0.000387              0.021775        1  Eicher Motors
16            0.000315              0.020703        1      HDFC Life
25            0.000572              0.022309        1            M&M
26            0.000177              0.021146        1  Maruti Suzuki
29            0.000013              0.025678        1           ONGC
40            0.000278              0.020248        1  Tech Mahindra
43            0.000211              0.024154        1            UPL
Cluster 2:
    Avg_Rate_of_return  Risk (Standard dev.)  cluster           company
2             0.000677              0.017798        2  Asian Paints Ltd
4             0.000302              0.017503        2    Bajaj Auto Ltd
8             0.000336              0.016582        2         Britannia
9             0.000485              0.017661        2             Cipla
10            0.000520              0.019248        2        Divis Labs
11            0.000552              0.016703        2    Dr Reddys Labs
14            0.000716              0.018200        2          HCL Tech
15            0.000430              0.018128        2         HDFC Bank
18            0.000385              0.015683        2               HUL
20            0.000648              0.018851        2           Infosys
21            0.000318              0.017516        2               ITC
23            0.000342              0.019667        2    Kotak Mahindra
24            0.000498              0.018813        2            Larsen
27            0.000627              0.014943        2            Nestle
28            0.000381              0.018446        2              NTPC
30            0.000491              0.017778        2   Power Grid Corp
31            0.000645              0.020423        2          Reliance
32            0.000588              0.019301        2   SBI Life Insura
34            0.000446              0.019495        2     Shree Cements
39            0.000469              0.016406        2               TCS
42            0.000668              0.019057        2  UltraTech Cement
44            0.000257              0.018416        2             Wipro
Cluster 3:
    Avg_Rate_of_return  Risk (Standard dev.)  cluster              company
0             0.000633              0.026180        3  Adani Ports Sez Ltd
5             0.000739              0.026745        3        Bajaj Finance
6             0.000669              0.025181        3        Bajaj Finserv
17            0.000751              0.027654        3  Hindalco Industries
22            0.000882              0.025312        3            JSW Steel
33            0.000645              0.023008        3                  SBI
37            0.000838              0.031658        3          Tata Motors
38            0.000715              0.026468        3           Tata Steel

C:\Users\MOUMITA\AppData\Local\Temp\ipykernel_14928\3004924344.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop('cluster', axis=1, inplace=True)

Best Portfolio: ['Axis Bank', 'Eicher Motors', 'HDFC Life', 'M&M', 'Maruti Suzuki', 'Tech Mahindra', 'UPL']
Average Rate of Return: 0.002139
Risk (Standard dev.): 0.15578

In [11]:
# Mean-Variance Optimization for Portfolio Weights
import cvxopt as opt
from cvxopt import blas, solvers

returns = np.array([companies[company][0] for company in best_portfolio_companies])
risks = np.array([companies[company][1] for company in best_portfolio_companies])

n = len(best_portfolio_companies)

# Convert to cvxopt matrices
S = opt.matrix(np.diag(risks))
pbar = opt.matrix(returns)

# Create constraint matrices
G = -opt.matrix(np.eye(n))   # negative n x n identity matrix
h = opt.matrix(0.0, (n ,1))
A = opt.matrix(1.0, (1, n))
b = opt.matrix(1.0)

In [12]:
# Calculate optimal weights
sol = solvers.qp(S, -pbar, G, h, A, b)
weights = np.array(sol['x']).flatten()

print("Optimal Weights for Minimizing Risk:")
for company, weight in zip(best_portfolio_companies, weights):
    print(f"{company}: {weight:.4f}")

     pcost       dcost       gap    pres   dres
 0:  1.2834e-03 -9.9897e-01  1e+00  4e-16  3e+00
 1:  1.2832e-03 -8.9678e-03  1e-02  2e-16  3e-02
 2:  1.2746e-03  1.0307e-03  2e-04  6e-17  7e-04
 3:  1.2701e-03  1.2658e-03  4e-06  5e-17  9e-06
 4:  1.2701e-03  1.2701e-03  4e-08  2e-16  9e-08
Optimal solution found.
Optimal Weights for Minimizing Risk:
Axis Bank: 0.1199
Eicher Motors: 0.1488
HDFC Life: 0.1530
M&M: 0.1535
Maruti Suzuki: 0.1433
Tech Mahindra: 0.1546
UPL: 0.1268